import React from "react"

import pet from "./assets/modality-cubes/pet-scan.jpg"
import eeg from "./assets/modality-cubes/eeg.jpg"
import ieeg from "./assets/modality-cubes/ieeg.jpg"
import mri from "./assets/modality-cubes/mri.jpg"
import meg from "./assets/modality-cubes/meg.jpg"
import nirs from "./assets/modality-cubes/nirs.jpg"

export const portalContent = {
  mri: {
    modality: "mri",
    className: "search-page-mri",
    portalName: "MRI",
    portalPrimary: "",
    publicDatasetStat: 100,
    participantsStat: 1100,
    hexBackgroundImage: mri,
    swoopBackgroundColorLight: "rgba(109,83,156,1)",
    swoopBackgroundColorDark: "rgba(45,34,64,1)",
    communityHeader: null,
    communityPrimary: null,
    communitySecondary: null,
  },
  eeg: {
    modality: "eeg",
    className: "search-page-eeg",
    portalName: "EEG",
    portalPrimary: "",
    publicDatasetStat: 100,
    participantsStat: 1100,
    hexBackgroundImage: eeg,
    swoopBackgroundColorLight: "rgba(109,83,156,1)",
    swoopBackgroundColorDark: "rgba(45,34,64,1)",
    communityHeader: null,
    communityPrimary: null,
    communitySecondary: null,
  },
  ieeg: {
    modality: "ieeg",
    className: "search-page-ieeg",
    portalName: "iEEG",
    portalPrimary: "",
    publicDatasetStat: 100,
    participantsStat: 1100,
    hexBackgroundImage: ieeg,
    swoopBackgroundColorLight: "rgba(109,83,156,1)",
    swoopBackgroundColorDark: "rgba(45,34,64,1)",
    communityHeader: null,
    communityPrimary: null,
    communitySecondary: null,
  },
  meg: {
    modality: "meg",
    className: "search-page-meg",
    portalName: "MEG",
    portalPrimary: "",
    publicDatasetStat: 100,
    participantsStat: 1100,
    hexBackgroundImage: meg,
    swoopBackgroundColorLight: "rgba(109,83,156,1)",
    swoopBackgroundColorDark: "rgba(45,34,64,1)",
    communityHeader: null,
    communityPrimary: null,
    communitySecondary: null,
  },
  pet: {
    modality: "pet",
    className: "search-page-pet",
    portalName: "PET",
    portalPrimary: "",
    publicDatasetStat: 100,
    participantsStat: 1100,
    hexBackgroundImage: pet,
    swoopBackgroundColorLight: "rgba(109,83,156,1)",
    swoopBackgroundColorDark: "rgba(45,34,64,1)",
    communityHeader: null,
    communityPrimary: null,
    communitySecondary: null,
  },
  nirs: {
    modality: "nirs",
    className: "search-page-nirs",
    portalName: "NIRS",
    portalPrimary: "",
    publicDatasetStat: 100,
    participantsStat: 1100,
    hexBackgroundImage: nirs,
    swoopBackgroundColorLight: " rgb(68, 114, 143)",
    swoopBackgroundColorDark: " rgb(36, 80, 108)",
    communityHeader: null,
    communityPrimary: null,
    communitySecondary: null,
  },
}
