apiVersion: v1
name: dbp-test
version: 1.8.0
description: test deployment chart
home: https://dbp.openneuro.org
sources:
  - https://github.com/poldracklab/digitalbrainproject
appVersion: 0.0.2
dependencies:
  - name: redis
    version: 22.0.7
    repository: https://charts.bitnami.com/bitnami
