apiVersion: v1
name: dbp-test
version: 1.8.0
description: test deployment chart
home: https://digitalbrainlife.openfmri.org
sources:
  - https://github.com/rwblair/openneuro
appVersion: 0.0.1
dependencies:
  - name: redis
    version: 22.0.7
    repository: https://charts.bitnami.com/bitnami
