name: Build Docker Images
on:
  push: { branches: [dbp] }
  pull_request: { branches: [dbp] }
jobs:
  build_server:
    name: Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: build the docker image
        id: build-docker-image
        run: |
          docker build -t ${{ github.repository }}/node:latest .
          docker build -t ${{ github.repository }}/server:latest packages/openneuro-server
  build_app:
    name: App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: build the docker image
        id: build-docker-image
        run: |
          docker build -t ${{ github.repository }}/node:latest .
          docker build -t ${{ github.repository }}/app:latest packages/openneuro-app
  build_indexer:
    name: Indexer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: build the docker image
        id: build-docker-image
        run: |
          docker build -t ${{ github.repository }}/node:latest .
          docker build -t ${{ github.repository }}/indexer:latest packages/openneuro-indexer
  build_datalad_service:
    name: Datalad Service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: build the docker image
        id: build-docker-image
        run: |
          cd services/datalad
          docker build --build-arg LERNA_JSON="$(cat ../../lerna.json)" -t ${{ github.repository }}/datalad-service:latest .
