name: Publish Docker Images
on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - dbp

jobs:
  build_server:
    name: Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: login to registry
        id: docker-hub
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build the docker image
        id: build-docker-image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/node:latest .
          docker build -t ghcr.io/${{ github.repository }}/server:${{ github.ref_name }} packages/openneuro-server
      - name: push the docker image
        id: push-docker-image
        run: docker push ghcr.io/${{ github.repository }}/server:${{ github.ref_name }}
  build_app:
    name: App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: login to registry
        id: docker-hub
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build the docker image
        id: build-docker-image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/node:latest .
          docker build -t ghcr.io/${{ github.repository }}/app:${{ github.ref_name }} packages/openneuro-app
      - name: push the docker image
        id: push-docker-image
        run: docker push ghcr.io/${{ github.repository }}/app:${{ github.ref_name }}
  build_indexer:
    name: Indexer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: login to registry
        id: docker-hub
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build the docker image
        id: build-docker-image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/node:latest .
          docker build -t ghcr.io/${{ github.repository }}/indexer:${{ github.ref_name }} packages/openneuro-indexer
      - name: push the docker image
        id: push-docker-image
        run: docker push ghcr.io/${{ github.repository }}/indexer:${{ github.ref_name }}
  build_datalad_service:
    name: Datalad Service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: login to registry
        id: docker-hub
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build the docker image
        id: build-docker-image
        run: |
          cd services/datalad
          docker build --build-arg LERNA_JSON="$(cat ../../lerna.json)" -t ghcr.io/${{ github.repository }}/datalad-service:${{ github.ref_name }} .
      - name: push the docker image
        id: push-docker-image
        run: docker push ghcr.io/${{ github.repository }}/datalad-service:${{ github.ref_name }}
